language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '6'

addons:
  browserstack:
    username: eemeliaro2
    access_key:
      secure: 'Vb1k4A+1vG1Vk3XxQDOvyt6bEzraxZIQTsYlLxTtNX7sf/g6r1Sf7DjN4+F4Hp6VnckAOTJce6L2cUba3XDeNylrtdQmgCw6mtHR5qguokVaN4r800rNgtrBabBI9RhSXsShjJPM8zBHrNF0jVZ/nSh6w6jiHuh2tDqmQjsuaNc='

before_script:
  - npm run prepare # not automatic on npm <4

script:
  - npm test
  - npm run lint

jobs:
  include:
    - stage: BrowserStack
      node_js: node
      script:
        - npm run build
        - npx serve &
        - sleep 2
        - npx mocha-selenium-bridge -d ./test/browser/browserstack-driver.js http://localhost:5000/test/browser/selenium.html
